import { AfterViewInit, ChangeDetectorRef, ElementRef, OnInit } from '@angular/core';
import { EmojiCategory } from '@ctrl/ngx-emoji-mart/ngx-emoji/data/data.interfaces';
import { Emoji } from '@ctrl/ngx-emoji-mart/ngx-emoji/emoji.component';
import { EmojiService } from '@ctrl/ngx-emoji-mart/ngx-emoji/emoji.service';
import { EmojiFrequentlyService } from './emoji-frequently.service';
export declare class CategoryComponent implements OnInit, AfterViewInit {
    ref: ChangeDetectorRef;
    private emojiService;
    private frequently;
    emojis?: any[] | null;
    hasStickyPosition: boolean;
    name: string;
    native: boolean;
    perLine: number;
    recent: string[];
    custom: any[];
    i18n: any;
    id: any;
    hideObsolete: boolean;
    emojiNative?: Emoji['native'];
    emojiSkin?: Emoji['skin'];
    emojiSize?: Emoji['size'];
    emojiSet?: Emoji['set'];
    emojiSheetSize?: Emoji['sheetSize'];
    emojiForceSize?: Emoji['forceSize'];
    emojiTooltip?: Emoji['tooltip'];
    emojiOver: Emoji['emojiOver'];
    emojiLeave: Emoji['emojiLeave'];
    emojiClick: Emoji['emojiClick'];
    container?: ElementRef;
    label?: ElementRef;
    containerStyles: any;
    labelStyles: any;
    labelSpanStyles: any;
    parent?: Element;
    margin: number;
    minMargin: number;
    maxMargin: number;
    top: number;
    constructor(ref: ChangeDetectorRef, emojiService: EmojiService, frequently: EmojiFrequentlyService);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    memoizeSize(): void;
    handleScroll(scrollTop: number): boolean;
    getEmojis(): any[];
    updateDisplay(display: 'none' | 'inherit'): void;
    trackById(index: number, item: any): any;
}
